version: "3.3"

services:

  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/files/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - .:/var/www/html:delegated
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php

  php:
    build: docker/php
    restart: always
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "9001:9000"
    links:
      - mysql
    environment:
      PHP_IDE_CONFIG: serverName=Heifetz
      XDEBUG_SESSION: docker-server
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_CONFIG: "client_host=${XDEBUG_CLIENT_HOST}"

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.23
    restart: always
    env_file:
      - '.env'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
